#!/usr/bin/php
<?php

# Copyright 2019 Mobimentum Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require_once(dirname(__FILE__) . '/hooks-config.php');
require_once(dirname(__FILE__) . '/hooks-lib.php');

// https://gerrit.googlesource.com/plugins/hooks/+/refs/heads/stable-3.0/src/main/resources/Documentation/hooks.md
print "### HOOK CHANGE-MERGED START " . __FILE__ . "\n";

// Check required params
$paramsOk = TRUE;
if (empty($config['url'])) $paramsOk = missingParam('gitlab-config', 'url');
if (empty($config['token'])) $paramsOk = missingParam('gitlab-config', 'token');
if (empty($opts['project'])) $paramsOk = missingParam('param', 'project');
if (empty($opts['change-url'])) $paramsOk = missingParam('param', 'change-url');

if ($paramsOk) {
	// Get project ID and branch name
	$projectId = getProjectId($opts['project']);

	// Delete remote branches
	if ($projectId) {
		deleteGitlabBranches($projectId, $opts['change-url']);
	}
	else print "Project {$opts['project']} NOT FOUND!\n";
}

print "### HOOK CHANGE-MERGED END\n\n";

?>
